### ISSUE TITLE
Support IntelliJ  2021.2

### ISSUE THREAD

**Issue by KylinDC** [eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator#23]
In IntelliJ 2021.2 can not search out this plugin in plugin marketplace, and install manually will meets error like:
![image](https://user-images.githubusercontent.com/11394149/128807352-2d2603a4-0771-4964-a78c-30a2b9b64942.png)

**Comment by eirikb** [comment]
Hi. Thanks.
It's because of [pluginUntilBuild = 211.*](https://github.com/eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator/blob/main/gradle.properties#L8).  
The reason I have this (I didn't before) is simply because wise JetBrains people told me it was best practice.  
I'm thinking about removing the setting all together, to be honest I don't see the point, if it works it works.

However I'm struggling a bit, since nothing builds. I get some errors in GitHub Actions, and others locally. I converted project from plain Java to Kotlin, and then with Gradle based on the plugin GitHub template so I'm a bit out of control when it fails like this.

**Comment by KylinDC** [comment]
Thanks for your work!

Base your `Feature/2021.2` branch, I have upgrade java version to 11 from 1.8 when GitHub action do the verification, and it passed the verification successfully! Please review this [pull request](https://github.com/eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator/pull/25) and check it with GitHub action.

**Comment by eirikb** [comment]
Thank you. Saw there was a fix for template repo with the same change, so the version I copied doesn't actually work.  
The "latest" for verification didn't seem to work, so I merged your branch into mine and changed it to **2021.2**.  
After some clumsy releasing I was able to push a release, and hopefully it works.  
Keeping this issue open until it's verified.  

So much hassle to change a setting I never wanted...

**Comment by KylinDC** [comment]
Thank you. Hope the release works fine. 
Need change every time after IDEA update is very unreasonable.

**Comment by KylinDC** [comment]
It works fine in my project, thank you so much for your work.

**Comment by eirikb** [comment]
Yes saw that, very weird. Here is the error I got: https://github.com/eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator/runs/3303762959?check_suite_focus=true

**Comment by eirikb** [comment]
Works fine for me in **2021.2** (build 212.4746.92). Closing
