### ISSUE TITLE
Support WS-222

### ISSUE THREAD

**Issue by demensky** [eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator#76]
Installing the version from the store installs version 1.4.1. When trying to install version 1.8.0 from a file, the following error is displayed:

<img width="486" alt="Error example" src="https://user-images.githubusercontent.com/10235949/180665805-ce0dc7a4-04b1-4151-a3e4-bc3d49c88174.png">

**Comment by eirikb** [comment]
Thanks, will look into it

**Comment by eirikb** [comment]
Wait, version 222, is this EAP?

**Comment by demensky** [comment]
<img width="538" alt="Снимок экрана 2022-07-25 в 14 00 07" src="https://user-images.githubusercontent.com/10235949/180762114-935b7756-377c-4908-8c92-a7333eef4648.png">

**Comment by eirikb** [comment]
RC as in release candidate?
I update the extension for each major version, and 222 is not out yet as far as I know.

The whole version limit thing is bothering me all the time. I wanted to have '*', but was discouraged, and now I have a old version with that, and a new version without.
That's why it wants to install ancient 1.4.1 version, which points to '*'.
(That's when I upgraded the code base).
I will bump to 222, that will fix the issue until 223 :)
